// <auto-generated />
using System;
using Game.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Game.Infrastructure.Entities.GameEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHumanPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcFactions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TerritoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinnerFactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WinnerFactionName")
                        .HasColumnType("TEXT");

                    b.Property<double>("WinningControlPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.GamePlayerEntity", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedTerritoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.MatchSnapshotEntity", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FactionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastTerritoryMovementUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SnapshotGeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerritoryOwnersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("MatchSnapshots");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.NpcTickCountEntity", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TickCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "FactionId");

                    b.ToTable("NpcTickCounts");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.PostcodeTerritoryEntity", b =>
                {
                    b.Property<string>("MapArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerritoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundaryCoordinatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Road")
                        .HasColumnType("TEXT");

                    b.HasKey("MapArea", "TerritoryId");

                    b.HasIndex("MapArea");

                    b.ToTable("PostcodeTerritories");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.TerritoryFeatureEntity", b =>
                {
                    b.Property<string>("MapArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerritoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Airports")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaSquareKm")
                        .HasColumnType("REAL");

                    b.Property<int>("BridgesOrTunnels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CastlesOrForts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chokepoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommercialAreas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Connections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Factories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmlandOrResources")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GovernmentSites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndustrialSites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MilitarySites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mountains")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Offices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PopulationSupport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ports")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Railways")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Roads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shops")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialFeatures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsArmyGrowthPerTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsEconomy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsMobility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsRevenuePerTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatsStrategicValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrbanDensity")
                        .HasColumnType("INTEGER");

                    b.HasKey("MapArea", "TerritoryId");

                    b.HasIndex("MapArea");

                    b.ToTable("TerritoryFeatures");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.GamePlayerEntity", b =>
                {
                    b.HasOne("Game.Infrastructure.Entities.GameEntity", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Game.Infrastructure.Entities.GameEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
