namespace Game.Domain;

public sealed record TerritoryFeatureSummary(
    int Factories,
    int Shops,
    int CommercialAreas,
    int Offices,
    int IndustrialSites,
    int FarmlandOrResources,
    int PopulationSupport,
    int Mountains,
    int Hills,
    int MilitarySites,
    int CastlesOrForts,
    int GovernmentSites,
    int Chokepoints,
    int UrbanDensity,
    int Roads,
    int Railways,
    int BridgesOrTunnels,
    int Airports,
    int Ports,
    int Connections,
    double AreaSquareKm,
    int SpecialFeatures)
{
    public static TerritoryFeatureSummary Empty { get; } = new(
        Factories: 0,
        Shops: 0,
        CommercialAreas: 0,
        Offices: 0,
        IndustrialSites: 0,
        FarmlandOrResources: 0,
        PopulationSupport: 0,
        Mountains: 0,
        Hills: 0,
        MilitarySites: 0,
        CastlesOrForts: 0,
        GovernmentSites: 0,
        Chokepoints: 0,
        UrbanDensity: 0,
        Roads: 0,
        Railways: 0,
        BridgesOrTunnels: 0,
        Airports: 0,
        Ports: 0,
        Connections: 0,
        AreaSquareKm: 0,
        SpecialFeatures: 0);
}
